name: "Release"

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "!v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup gcc"
      shell: bash
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10

    - name: "Test project"
      run: make test

    - name: "Build project"
      run: make build

    - name: "Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          dist/app*
